### ISSUE TITLE
All Subdecks of a main deck are not detected in the drop down

### ISSUE THREAD

**Issue by Eejya** [BSCrumpton/Deadline2#1]
Hi,
I have a hierarchical structure for my decks which are then under a Master deck. Something like this:

![image](https://user-images.githubusercontent.com/3821801/78008215-061df200-735d-11ea-88fb-255c869d9736.png)
I wanted to use the deadline configuration for the Master deck but, when I open the deadline configuration to select a deck, the drop down shows some of the subdecks of the Master deck (but not all). 

![image](https://user-images.githubusercontent.com/3821801/78008556-6ad94c80-735d-11ea-948a-93c3edbbafcf.png)

Changing the layout right now with my exams near the corner wouldn't be possible and I'd prefer to keep my decks in the same hierarchy because it is easier to divide subjects by theme.

Am I missing some configuration here or is this functionality not supported at the moment?

Appreciate the help!

**Comment by BSCrumpton** [comment]
@Eejya 
The functonality doesn't currently exist to have a deadline apply for all subdecks in a chosen master deck. The closest you could get is just applying individual deadlines to all the subdecks. 

Note that if requested enough; I could add in the functionality you need. My main worry was that it might do some unintended things if you for example: put a deadline on a TOP level deck (like the overall deck in anking), wiping out all deadlines for sub decks. 

As for why some of your sub decks aren't showing up: Do those decks have cards in them? The code is currently setup to ONLY pull decks with cards in them, not decks with subdecks having cards. 
If the deck itself has cards and isn't showing up; let me know and we can debug some.

**Comment by Eejya** [comment]
@BSCrumpton Thanks for the quick reply.

Regarding the subdecks which show up, you're right. They do have cards directly under them which is why they're specifically showing up.

Feel free to close the issue if you'd like.

**Comment by BSCrumpton** [comment]
@Eejya  will do. However, I'll add myself a possible update to include hierarchical master decks in addition to decks with cards. This would also require the functionality of adding a deadline to all subdecks. 

I just want to make sure that the code behaves in a way that users expect and can understand. 

thanks for reaching out!
