### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Limormak** [BSCrumpton/Deadline2#10]
I am trying to download the add on but for some reason the drop-down menu to choose which deck I want to put a deadline for won't work and then when I press ok Anki tells me that there is an issue with the add on and that I should press shift when opening Anki again so that it will disable the add ons. I really want this add-on to work so please help!

**Comment by BSCrumpton** [comment]
@Limormak  what version of anki do you have? Could you paste a screenshot of the error message?

**Comment by Limormak** [comment]
<img width="471" alt="Screen Shot 2021-01-15 at 12 09 48 PM" src="https://user-images.githubusercontent.com/77478133/104757136-ac8b8600-572a-11eb-85cb-b9317e58e465.png">

**Comment by Limormak** [comment]
Im Pretty sure I have the latest version, I just downloaded it

**Comment by BSCrumpton** [comment]
It's possible that the new update clashes with my code. To verify, Was there anything more to the error message? Typically they have a line printout or something like that. 

Regardless, after work today I'll try and troubleshoot. In the meanwhile, you're welcome to try an older version of anki.

**Comment by Limormak** [comment]
<img width="455" alt="Screen Shot 2021-01-15 at 12 27 15 PM" src="https://user-images.githubusercontent.com/77478133/104758858-042af100-572d-11eb-8ee9-19410d473991.png">


yup this is the rest of it! Thanks so much!

**Comment by Limormak** [comment]
I download the older version and for some reason, the same thing is happening

**Comment by BSCrumpton** [comment]
my recommendation would be to go into the deadline config, delete the existing deadlines you have and then restart anki (new or old version). You should be able to add new deadlines without issue. 

Did you happen to remove any decks recently, or change their name?

**Comment by Limormak** [comment]
I just tried that and the error message keeps popping up. Sorry to bother you Im just not sure why it keeps doing this.

**Comment by Limormak** [comment]
<img width="278" alt="Screen Shot 2021-01-15 at 2 16 04 PM" src="https://user-images.githubusercontent.com/77478133/104768784-3a23a180-573c-11eb-804d-1eac115a7c51.png">
 this is what happens since it wont let me select a deck

**Comment by BSCrumpton** [comment]
@Limormak  can you describe what you seen when you're trying to create deadlines? I've just updated my anki and don't have any issues.

**Comment by BSCrumpton** [comment]
I'm going to close this as there hasn't been any progress. Feel free to re-open if you'd like!
