### ISSUE TITLE
Unable to delete deadlines

### ISSUE THREAD

**Issue by cookieandmonster** [BSCrumpton/Deadline2#14]
When I go back to Tools > Deadlines, the deadlines are no longer there and I can't delete the ones I made.

**Comment by BSCrumpton** [comment]
did this just start happening recently? 

can you post your anki version and potentially a screenshot of the deadline config screen directly after adding the deadline, then again after re-opening anki?

For what it's worth; i'm currently on anki 2.1.44 and I'm not having any issues.

**Comment by BSCrumpton** [comment]
As there have been no updates for almost a year, I'm going to close this issue.
