### ISSUE TITLE
Delete a schedule ignored 'are you sure?' dialogue

### ISSUE THREAD

**Issue by dharrison4** [BSCrumpton/Deadline2#16]
Gif demonstrates:
![deadline2Whoopsie](https://user-images.githubusercontent.com/6942985/147627075-b658032e-80a9-47c8-82f9-d7a4a07ddbe4.gif)

Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 Py
Deadline2 version is current (release 2021-05-02)

**Comment by BSCrumpton** [comment]
Taking a look into this now

**Comment by BSCrumpton** [comment]
@dharrison27 I'm not currently able to reproduce. Can you give me an example of your workflow? Using multiple devices, decks, other addons etc.

**Comment by dharrison4** [comment]
> @dharrison27 I'm not currently able to reproduce. Can you give me an example of your workflow? Using multiple devices, decks, other addons etc.

Hi there! Sure, I'll list it all as best I can.

Anki on Windows
Ankidroid

Windows anki addons are:
https://imgur.com/a/4yXQEKC

I wanted to point out, also, that the line gets deleted before the dialogue box pops up.

**Comment by BSCrumpton** [comment]
I believe this is caused by needing to do a resync of your DB prior to messing with deadlines- If anyone else has this issue with the new version; please open a new issue and we'll see if we can reproduce.
