### ISSUE TITLE
Add to all sub decks 

### ISSUE THREAD

**Issue by burnhamnate** [BSCrumpton/Deadline2#18]
Hey I just looked into this addon and I think it is awesome. The only issue that I am seeing is that when I go to add it to a deck, it doesn't show me all the decks I have under one large deck. Example: I have a psychology deck with various units. It would be nice to be able to add the due date to all the decks at once.

**Comment by BSCrumpton** [comment]
this should be fixed by #7  when I finish it- closing this one as a result.
