### ISSUE TITLE
Error when downloading from Anki code

### ISSUE THREAD

**Issue by wyattkim** [BSCrumpton/Deadline2#20]
I keep getting the same error below when I try to download this add on. Any ideas on how to fix this? I'm on Anki version 2.1.54.
<img width="577" alt="Screen Shot 2022-08-16 at 9 36 20 PM" src="https://user-images.githubusercontent.com/10524591/185015526-71543fce-882a-4843-ba30-05cd9f8b288c.png">

**Comment by BSCrumpton** [comment]
Going to generally close this issue- It wouldn't be any issue with the add on itself since it is hosted not by me. Hope your issue got solved eventually!
