### ISSUE TITLE
Deadline2 Add-On Error

### ISSUE THREAD

**Issue by paullyb17** [BSCrumpton/Deadline2#21]
Hi! I am on Anki version:
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 5.14.1 PyQt 5.14.1

When I try to create or process a deadline, I get this error:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.5.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-30 01:01:21
Add-ons possibly involved: ⁨Deadline2⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/paulbowman/Library/Application Support/Anki2/addons21/723639202/config.py", line 130, in onDelete
    delConfId=mw.col.decks.byName(deck)['conf']
KeyError: 'conf'

Any and all help would be appreciated!

**Comment by tb9ce** [comment]
Hi, did you ever figure out the issue?

Thanks!

**Comment by BSCrumpton** [comment]
I'm unable to reproduce this won windows 10 with the following versions:

```
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
```

**Comment by BSCrumpton** [comment]
@paullyb17  @tb9ce a weird thing I'm noticing here- that error message has a different `byName` method than I actually use. Can you confirm what version of the addon you have?

**Comment by BSCrumpton** [comment]
no response, closing for now.
