### ISSUE TITLE
Says deck with 2300 new cards does not have any new cards due

### ISSUE THREAD

**Issue by miahen** [BSCrumpton/Deadline2#22]
I have been trying to use this for a few days. It says my deck with 2300 new cards does not have any new cards due. I disabled all add-ons, and it still isn't working. Please please please help me. Says 0 new cards, then automatically changes the actual deck so instead of showing 2300 new cards, says 1 new card (on the home page). Then the process deadline = 0 new cards. I looked at [https://github.com/BSCrumpton/Deadline2/issues/5] but the explanation wasn't clear.

**Comment by BSCrumpton** [comment]
closing this issue. Unsure if it still persists; if so the user can create a new ticket.
