### ISSUE TITLE
Issue when i create  a new deadline

### ISSUE THREAD

**Issue by Elouan3** [BSCrumpton/Deadline2#23]
Error is :

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-21 14:10:58

Caught exception:
Traceback (most recent call last):
  File "C:\Users\eloua\AppData\Roaming\Anki2\addons21\723639202\config.py", line 113, in onAdd
    deckId=mw.col.decks.byName(deck)['id']
TypeError: 'NoneType' object is not subscriptable

Also it doesn't recognize all my decks ...

**Comment by BSCrumpton** [comment]
I'm upgrading my anki now to take a look- it for sure works with the following:
```
Version ⁨2.1.52 (ab1c2395)⁩
Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
```

hopefully it's not a pyqt 6 issue.

**Comment by BSCrumpton** [comment]
@Elouan3  can you verify that error message? no where in my code do I use a `byName` sub method, but I do for sure use `by_name` which is different. Can you verify what version of the addon you actually have?

**Comment by Elouan3** [comment]
Hello, thank for you answers and your add-on 

My version was the one downloaded through Anki with the code process so the last one i guess. To be sure I replaced it by the one on the Github and now it show "by_name"  with this new error  : 
t
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-06-05 17:45:11

Caught exception:
Traceback (most recent call last):
  File "C:\Users\eloua\AppData\Roaming\Anki2\addons21\723639202\config.py", line 103, in onAdd
    deckId=mw.col.decks.by_name(deck)['id']
TypeError: 'NoneType' object is not subscriptable"

**Comment by BSCrumpton** [comment]
So, I've tested this as still good with the new 2.4 version. you can give it a shot with the upgrade, and if it still persists open a new ticket.
