### ISSUE TITLE
Continued issue with the new update

### ISSUE THREAD

**Issue by isasanki** [BSCrumpton/Deadline2#27]
Hi ! i saw that you had just updated your add-on ! thank you so much. I am still having issues with it however, it still cant find any updates and wont work with the new anki update... Do you know why this could be happening ?

**Comment by Koorosh-J** [comment]
Thanks a lot for the new update, but I still have the following error at anki startup with this fantastic add-on:

Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Linux-6.5.0-14-generic-x86_64-with-glibc2.35

When loading Deadline2:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/home/user/.local/share/Anki2/addons21/723639202/__init__.py", line 12, in <module>
    from PyQt5.QtWidgets import *
ModuleNotFoundError: No module named 'PyQt5'

**Comment by BSCrumpton** [comment]
heya, I haven't yet updated to make the addon work with PyQT6, nor anki 23.X. I'm doing that now!

**Comment by nyxaria** [comment]
hi whats the progress please?

**Comment by BSCrumpton** [comment]
@nyxaria  can you give the new update a shot? 
@Koorosh-J  and @isasanki as well please!

**Comment by BSCrumpton** [comment]
If it doesn't work, feel free to open a new issue now!

**Comment by Koorosh-J** [comment]
Thanks a lot, for me it worked again and saved my life
