### ISSUE TITLE
Anki 2.1.22: AttributeError: 'DeckManager' object has no attribute 'all_config'

### ISSUE THREAD

**Issue by ijgnd** [BSCrumpton/Deadline2#3]
I don't use this add-on. I browsed the official forum on tenderapp and saw this bug report. I repost here just in case you missed this. 

https://anki.tenderapp.com/discussions/add-ons/44195-anki-deadline-add-on-glitch

a relevant commit might be: https://github.com/ankitects/anki/commit/333d0735ffbc160d629abe5ae4a5fdfd5a1300ac

**Comment by BSCrumpton** [comment]
yeah; that was due to the update last night. I thought I had set the new version to only apply to anki 2.1.25+, so that it wouldn't update folks on older versions (like that issue). I'll get that sorted. Thank you for the heads up!

**Comment by BSCrumpton** [comment]
this has now been fixed; I properly set up split versioning for the older version.
