### ISSUE TITLE
It says no new cards even when there are

### ISSUE THREAD

**Issue by bprosr12** [BSCrumpton/Deadline2#5]
<img width="499" alt="image" src="https://user-images.githubusercontent.com/69193615/89276507-a487d000-d63b-11ea-9b3d-3f15e4db2cc1.png">

I can see the decks I want to add a deadline to, but even though there are definitely cards that I haven't seen and I have also done some new cards today.

Thanks for any support.

**Comment by BSCrumpton** [comment]
@bprosr12 would you mind sending a screenshot of the option group for any of the decks with 0 cards per day? I'm wondering if you're having the issue of subdecks not showing new cards because of a top level deck configuration missing or something like that.

**Comment by bprosr12** [comment]
![image](https://user-images.githubusercontent.com/69193615/89299463-97c8a380-d65e-11ea-9cd6-d8c3e7543c37.png)

Here is my deck list. For simplicity's sake I have only done the path for one sub-deck as they are all a little bit different (I have been trying to manually do a deadline system, so a lot of the small sub-decks (like vocabulary &c) used to have their own groups.

**CLASSICS option group**

<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89298601-6e5b4800-d65d-11ea-9aff-9bbb5910c1f3.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89298617-74e9bf80-d65d-11ea-87f1-4dd298a0cb12.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89298642-7b783700-d65d-11ea-944a-91e6a63c5d1d.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89298801-b9755b00-d65d-11ea-9a19-4d75f748f891.png">


CLASSICS::GREEK::Irregular Verbs group
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89299055-14a74d80-d65e-11ea-8938-a050e863fbeb.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89299075-1b35c500-d65e-11ea-9c02-479e402ab295.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89299128-27218700-d65e-11ea-9501-935b2aeabca4.png">
<img width="445" alt="image" src="https://user-images.githubusercontent.com/69193615/89299154-2f79c200-d65e-11ea-80b5-cf93dc75f532.png">

**Comment by bprosr12** [comment]
Hi I have just re-processed the add-on and now they are working for some reason. I think that there probably was some error with the parent decks and that by going thru and checking I have fixed it.

I think that the issue may have involved the fact that I already had some complicated deck options groups set up. I did notice that the options groups that your add-on created were not in fact selected in the options menu originally(I think that that might have been the bug). After I went back and switched the options group from the one I had made to the one created by the add-on (while taking those screenshots), and then did "process" in the add-on again it started working.

Thanks very much for the quick response - I fear that I have given you a very elusive bug to catch (if you choose to) - as well as one which is easily fixed by the user so probably not much point in doing it at all.

**Comment by BSCrumpton** [comment]
@bprosr12  The fact that my options group wasn't automatically applied is a relativity new bug (I first noticed it after this most recent update). I do think that was probably the problem in your case. 

Long term; I'm going to be just adjusting the option group of the deck as it sits instead of creating a new one (there have been quite a few people asking for this), which will solve that problem. 

Thanks for reaching out! I'd love to hear if you have any ideas on how I can make the addon better. Feel free to close this issue if you feel it is solved, and open another for potential changes.

**Comment by bprosr12** [comment]
Ok thanks very much - it works now and I am very happy with it. I don't think it really needs any more features, keep it simple! Rewriting an existing options group is definitely a great idea though.
