### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LeavesEatingCow** [BSCrumpton/Deadline2#6]
Does it still work? Whenever I put the deadline and process it tells me the amount of days I have left but all the other fields are 0. When I check the decks setting nothing changed.

**Comment by BSCrumpton** [comment]
what version of anki are you on? and for your deck, can you post a screenshot of your current settings for the deck? the new cards tab should be enough

**Comment by LeavesEatingCow** [comment]
I am on the latest one

**Comment by BSCrumpton** [comment]
gotcha. This may be broken in the newest update; i'll have to test after work today. 
Thats if it's not just an mis-configured setting

**Comment by LeavesEatingCow** [comment]
Alright. I'll screenshot to you once I'm done downloading something.

**Comment by LeavesEatingCow** [comment]
Here they are.
<img width="495" alt="deadline2" src="https://user-images.githubusercontent.com/69094343/92868951-500d0880-f3d0-11ea-92dd-24e20b87a135.PNG">
<img width="499" alt="deadline" src="https://user-images.githubusercontent.com/69094343/92868953-500d0880-f3d0-11ea-8a28-901654d6c668.PNG">

**Comment by BSCrumpton** [comment]
![image](https://user-images.githubusercontent.com/24260787/92869672-11c41900-f3d1-11ea-803c-3d144b045bac.png)
could you send something like the above?

**Comment by LeavesEatingCow** [comment]
Sorry I went to Sleep. Here they are.
<img width="586" alt="deadline" src="https://user-images.githubusercontent.com/69094343/92929833-30e19b80-f40f-11ea-91bb-910409da4115.PNG">
<img width="398" alt="deadline3" src="https://user-images.githubusercontent.com/69094343/92929836-317a3200-f40f-11ea-8100-5cae094037f7.PNG">

**Comment by BSCrumpton** [comment]
@LeavesEatingCow How many "New" cards are in the particular deck you're trying to test? My current thought is that your deadline is just too far away for the # of new cards you have; and upon rounding you're expected to do <1 card per day. Does this work with a much smaller deadline? try 5-15 days away.

**Comment by LeavesEatingCow** [comment]
@BSCrumpton It has 20 new cards per int. right now. Plus theres over 1000 cards in the deck. I put the deadline in around 100 days. Oh wait...Is that why? It would be less than the default setting i put(20). Let me do it for an earlier deadline.

**Comment by BSCrumpton** [comment]
for the basis of this addon, the # of cards in the deck doesn't really matter but the # of new cards in the deck does. 

The original foundation of this addon was just to ensure you've seen all new cards at least once by a certain deadline. Wasn't intended to hit ALL cards for a deck (unless they're all new). https://github.com/BSCrumpton/Deadline2/issues/4#issuecomment-636221296 somewhat talks about this

**Comment by LeavesEatingCow** [comment]
Yes. This is a new deck I downloaded with 1000+ cards I haven't seen yet.

**Comment by BSCrumpton** [comment]
can you change the new cards per day setting up to 999 or 9999 and re-run to see if that changes anything?

**Comment by LeavesEatingCow** [comment]
When you say re-run you mean restart? When I do that is it suppose to automatically revert the new cards setting since the new cards is too high?

**Comment by LeavesEatingCow** [comment]
Does the addon work for you?

**Comment by LeavesEatingCow** [comment]
I re ran the addon and it still shows 0's.

**Comment by BSCrumpton** [comment]
I haven't yet tested. Will get around to it after work today

**Comment by BSCrumpton** [comment]
![image](https://user-images.githubusercontent.com/24260787/92975938-64e0af00-f457-11ea-9e80-4f81be957e68.png)
@LeavesEatingCow were you ever getting any errors like the above when you were processing deadlines?

**Comment by LeavesEatingCow** [comment]
@BSCrumpton only when I deleted a date in the deadline

**Comment by LeavesEatingCow** [comment]
@BSCrumpton This is the error.
<img width="504" alt="deadline2" src="https://user-images.githubusercontent.com/69094343/92976090-c86adc80-f457-11ea-90c5-ed095e45d22d.PNG">

**Comment by BSCrumpton** [comment]
something is fishy with the addon currently. I'll be doing some dev work through tonight and will ping you back here when I think it's ready to try again.

**Comment by BSCrumpton** [comment]
@LeavesEatingCow Figured out the issue. Whenever you create a new deadline, it would typically change the Options group for each deck. The current issue is that the new options group isn't being saved. If you manually go to the dropdown in settings and set it to the deck name; it should process correctly.

**Comment by LeavesEatingCow** [comment]
Ok. I changed it now it does what the deadline shows. But it changed new cards to 0.
<img width="702" alt="deadline5" src="https://user-images.githubusercontent.com/69094343/92976971-bdb14700-f459-11ea-9871-111bc892cc4f.PNG">
<img width="589" alt="deadline4" src="https://user-images.githubusercontent.com/69094343/92976973-bdb14700-f459-11ea-930e-1653347ada62.PNG">
<img width="498" alt="deadline6" src="https://user-images.githubusercontent.com/69094343/92976976-be49dd80-f459-11ea-9627-9cf6d2b32c75.PNG">

**Comment by BSCrumpton** [comment]
@LeavesEatingCow Newest Deadline addon has been pushed to AnkiWeb. 
Would you be able to remove all of your current deadlines, install the update, restart anki and then try to create a new deadline?

**Comment by LeavesEatingCow** [comment]
Alright thanks! It works now.

**Comment by BSCrumpton** [comment]
awesome! I'm going to close this issue now. Feel free to open a new one if you encounter any issues!

Also feel free to drop a thumbs up on ankiweb if you'd like. https://ankiweb.net/shared/info/723639202
