### ISSUE TITLE
Not an issue. Add-on is awesome!

### ISSUE THREAD

**Issue by owlseyeMD** [BSCrumpton/Deadline2#7]
Is it possible to have the option to have all subdecks affected?

Thanks!

**Comment by BSCrumpton** [comment]
hey, @owlseyeMD , I'm glad you're finding use with the addon!

Per my comment here: https://github.com/BSCrumpton/Deadline2/issues/1#issuecomment-606577828
My original worry was about having unintended changes if folks did't know exactly what they were updating. 

However; after some thought I've realized I can just add a checkbox for any decks with subdecks, querying if you want to apply the deadline to all subdecks. Default would be no. 

This addition should be fairly easy to add, but I'm not 100% when I'll get around to it. Know that it is on the docket though! I'm hoping to have it done in the next month.

**Comment by BSCrumpton** [comment]
as a heads up, this is still on the docket. I didn't get around to it last month; but hopefully should this upcoming one!

**Comment by BSCrumpton** [comment]
@owlseyeMD As a heads up- I've tentatively started work on this. However, I'm thinking about a different method of implementation that will accomplish a similar result. 

How would you feel about being able to select multiple decks at once for a single deadline? think ctrl + click for multi selection etc. 
My current envisionment would make it hard to implement that at the same time as a recursive subdeck deadline application, but _should_ accomplish the same thing. 

If you think people would prefer both, I can still see about implementing both. 
As a heads up- this work is prompting a re-work of the menu templates that I've been using, which is slightly extending development time.

**Comment by burnhamnate** [comment]
Any update?

**Comment by BSCrumpton** [comment]
Finally working on this now

**Comment by BSCrumpton** [comment]
@owlseyeMD @burnhamnate  @camayl  I think my last push should fully finish this work. Just want to do some further testing before I release it to the world. Would any of y'all be interested in beta testing the update?

**Comment by BSCrumpton** [comment]
[Deadlinev2_4_2.zip](https://github.com/BSCrumpton/Deadline2/files/8821219/Deadlinev2_4_2.zip)
Just rename this file to have an .ankiaddon file type, and you should be able to locally install if if so.

**Comment by BSCrumpton** [comment]
merged the functionality. closing issue.
