### ISSUE TITLE
Shows all subdecks but does not show the main deck when setting the deadline

### ISSUE THREAD

**Issue by NfernoFire** [BSCrumpton/Deadline2#8]
I use Anking mainly and basically unsuspend cards as I need them based on tags (hence don't need the subdecks as much). This addon is great, however, it doesnt allow me set the deadline for the main anking deck. Can this be fixed? Thank you! 

![image](https://user-images.githubusercontent.com/21341806/103465534-60216d00-4d5e-11eb-9636-67567baf526d.png)

**Comment by BSCrumpton** [comment]
hey @NfernoFire, do you currently have cards in the overall AnKing deck? Currently the addon is configured to only allow you to set deadlines in decks (or subdecks) that contain cards- not that contain subdecks with cards. 

Is your goal here to apply the same deadline to all of the Anking Subdecks? If so; this should be accomplished whenever I make the updates for #7

**Comment by BSCrumpton** [comment]
For now i'm going to close this. Feel free to re-open if you'd like, or continue to have issues.
