### ISSUE TITLE
Spacing time till deadline

### ISSUE THREAD

**Issue by maekstra** [BSCrumpton/Deadline2#9]
Hey!
Would be awesome if such an amazing add-on (many, many thanks for it) had a feature to recalculate the spacing time for the cards before deadline. At least for first 5 good answers. 
One wouldn't need to work around the time by himself and first 5 good recalls is needed for good memorization of the concept.

Thanks!

**Comment by BSCrumpton** [comment]
Hey @maekstra, I'm glad you're finding good use with the addon! 

I'm not entirely sure if my addon can provide the functionality you seek. Realistically; my addon simply takes the "new" number for each deck, then divides it by # of days until the deadline. You would have to better control the query I do for card numbers, which I'm not sure is possible.

**Comment by BSCrumpton** [comment]
@maekstra  I'm going to go ahead and close this for now, since as far as I can tell, this is isn't functionality that I believe this addon should handle. Please feel free to open another ticket if you have any other ideas!
